name: Build android app

on: [push]

jobs:
  # Build App
  build:
    runs-on: windows-latest
    
    env:
      SERVICE_APP_KEY: ${{ secrets.SERVICE_APP_KEY }}
      APPLICATION_NAME: HelloAction
      PACKAGE_NAME: com.companyname.myapplication
      
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
          # cache: 'gradle'
          
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build Solution
        run: msbuild ${{ env.APPLICATION_NAME }}/${{ env.APPLICATION_NAME }}.sln /restore /p:Configuration=Release

      - name: Create and Sign the APK
        run: msbuild ${{ env.APPLICATION_NAME }}/${{ env.APPLICATION_NAME }}/${{ env.APPLICATION_NAME }}.Android\${{ env.APPLICATION_NAME }}.Android.csproj /p:Configuration=Release /p:OutputPath=bin\Release\

      - name: List folder content
        run: dir ${{ env.APPLICATION_NAME }}/${{ env.APPLICATION_NAME }}/${{ env.APPLICATION_NAME }}.Android\bin\Release

      - name: List object folder content
        run: dir ${{ env.APPLICATION_NAME }}/${{ env.APPLICATION_NAME }}/${{ env.APPLICATION_NAME }}.Android\obj\Release\android\bin

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyApplication.apk
          path: ${{ env.APPLICATION_NAME }}.Android\bin\Release\${{ env.PACKAGE_NAME }}-Signed.apk
