name: Build Xamarin.Android app

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:

    - name: setup-xamarin
      uses: maxim-lobanov/setup-xamarin@v1
      with:
        mono-version: latest # specify version in '<major>.<minor>' format
        xamarin-ios-version: latest # specify version in '<major>' format
        xamarin-mac-version: latest # specify 'latest' keyword to pick up the latest available version
        xamarin-android-version: latest # specify full version; it is not recomended option because your pipeline can be broken suddenly in future
        xcode-version: latest # set the latest available Xcode 11
    
    - uses: actions/checkout@v4
    - name: Set default Xamarin SDK versions
      run: |
        $VM_ASSETS/select-xamarin-sdk-v2.sh --mono=6.10 --android=13.0

    - name: Setup .NET Core SDK 5.0.x
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '5.0.x'

    - name: Install dependencies
      run: nuget restore HelloAction/HelloAction.sln

    - name: Build
      run: msbuild HelloAction/HelloAction/HelloAction.Android/HelloAction.Android.csproj /t:PackageForAndroid /p:Configuration=Debug
